### PR TITLE
Make config more generic

### PR DESCRIPTION
**Pull request by nandorojo**
I added the EAS steps here into a config plugin, helping address #5

### CODE REVIEW

**Comment by gaishimo** [comment]
Thanks!

I tried eas build with this fix, but it fails (profile not found).

XCode Log
```
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace ./EASWidgetExample.xcworkspace -scheme EASWidgetExample -configuration Release -destination generic/platform=iOS -archivePath "/Users/expo/Library/Developer/Xcode/Archives/2023-04-17/EASWidgetExample 2023-04-17 03.02.58.xcarchive" archive

User defaults from command line:
    IDEArchivePathOverride = /Users/expo/Library/Developer/Xcode/Archives/2023-04-17/EASWidgetExample 2023-04-17 03.02.58.xcarchive
    IDEPackageSupportUseBuiltinSCM = YES

Prepare packages

Computing target dependency graph and provisioning inputs

Create build description
Build description signature: 884e5877bc336948df13416de0551413
Build description path: /Users/expo/Library/Developer/Xcode/DerivedData/EASWidgetExample-ercyqgdwxcktircatyubvwvtyxyz/Build/Intermediates.noindex/ArchiveIntermediates/EASWidgetExample/IntermediateBuildFilesPath/XCBuildData/884e5877bc336948df13416de0551413-desc.xcbuild

note: Building targets in dependency order
warning: Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')
warning: Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EASWidgetExample' from project 'EASWidgetExample')
warning: Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EASWidgetExample' from project 'EASWidgetExample')
/Users/expo/workingdir/build/ios/EASWidgetExample.xcodeproj: error: No profiles for 'com.gaishimo.example1.widget' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.gaishimo.example1.widget'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'widget' from project 'EASWidgetExample')

```

**Comment by nandorojo** [comment]
not sure if this PR is the reason for that, is it?

Xcode couldn't find any iOS App Development provisioning profiles matching 'com.gaishimo.example1.widget'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'widget' from project 'EASWidgetExample')

you may have to delete the ios folder before running eas build. i’ll try it.

**Comment by gaishimo** [comment]
I ran the same eas build on the main branch and did not have the same error. (I have deleted the ios/ folder).

```
eas build --platform all --ios preview
```


I will investigate the cause too when I have time.

**Comment by maarten-22** [comment]
Hi, are there any plans to get this merged / published? :)

**Comment by gaishimo** [comment]
Sorry for leaving it as it is.

I tried to build today and no longer get build errors, so I will merge it in soon!

**Pull request merged**
